#!/bin/bash

echo ""
echo "Welcome to the FS-WATCHER Installer"
echo ""

VERSION=$(curl -Ls https://hnhdigital-os.github.io/fs-watcher/latest)

sudo curl -o /usr/local/bin/fs-watcher "https://hnhdigital-os.github.io/fs-watcher/download/${VERSION}/fs-watcher" && sudo chmod 755 /usr/local/bin/fs-watcher

/usr/local/bin/fs-watcher install

echo ""
echo "Installation complete."
echo ""
